docs_dir: docs/
repo_name: 'TranslationalAICenterISU/cv-ssl-aug-2023'
repo_url: 'https://github.com/TranslationalAICenterISU/cv-ssl-aug-2023'

site_name: 'ADLRG Mini-Course: Computer Vision & Self-supervised Learning'
site_description: 'Documentation for mini-course on - Computer Vision & Self-supervised Learning'
site_author: 'TrAC Team, CyVerse, & Midwest Big Data Summer School'
site_url: 'https://translationalaicenterisu.github.io/cv-ssl-aug-2023/'

edit_uri: edit/mkdocs/docs

# Copyright
copyright: 'Copyright &copy; 2023 Iowa State University'

# Navigation Page

nav:
  - 'Home': 
    - index.md 
  - 'Getting Started': 
    - 'Code of Conduct': getting_started/code_conduct.md
    - 'Logistics': getting_started/logistics.md
    - 'Schedule': getting_started/schedule.md
    - 'Resources': sections/resources.md
  - 'Sections':
    - '1. Introduction to CV': sections/m01_intro.md
    - '2. Object Tracking': sections/m02_tracking.md
    - '3. CLIP': sections/m03_clip.md
    - '4. Grounding Dino': sections/m04_grounding_dino.md
    - '5. Fast SAM': sections/m05_fast_sam.md
    - '6. Monodepth': sections/m06_monodepth.md
    - '7. Resources': sections/resources.md

# JavaScript for Intercom Widget
extra_javascript:
  - javascripts/intercom-learning.js
  
# Set theme to `readthedocs`
# must also set Action to use `@nomaterial` branch instead of `@master` for material
theme:
  name: material
# setting features for the navigation tab
  features:
    - navigation.instant
      #- navigation.expand
    - navigation.tracking
      #- navigation.sections
    - navigation.indexes
    - toc.integrate
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: material/corn

# Options
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/TranslationalAICenterISU/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
